name: 'CI setup'
runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        version: 2.2.5

    - name: Install dependencies
      shell: bash
      run: bun ci