name: Deploy Convex

on:
  push:
    branches:
      - main
    paths:
      - packages/app/convex/**
      - .github/workflows/deploy-convex.yml

concurrency:
  group: deploy-convex-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Deploy Convex
        working-directory: packages/app
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
        run: bunx convex deploy
