name: Deploy Convex

on:
  push:
    branches:
      - main
    paths:
      - packages/app/convex/**
      - .github/workflows/deploy-convex.yml

concurrency:
  group: deploy-convex-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/ci-setup
      - uses: ./.github/actions/ci-checks

      - name: Deploy Convex
        working-directory: packages/app
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
        run: bunx convex deploy
