name: Publish MCP Server

on:
  push:
    tags:
      - mcp-server-v*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.23"

      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run --filter @mirdor/memoria-mcp build

      - name: Publish to npm
        run: npm publish --workspace packages/mcp-server --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
